/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ComposableTable {
        "data": string;
        "itemsperpage": number;
    }
}
declare global {
    interface HTMLComposableTableElement extends Components.ComposableTable, HTMLStencilElement {
    }
    var HTMLComposableTableElement: {
        prototype: HTMLComposableTableElement;
        new (): HTMLComposableTableElement;
    };
    interface HTMLElementTagNameMap {
        "composable-table": HTMLComposableTableElement;
    }
}
declare namespace LocalJSX {
    interface ComposableTable {
        "data"?: string;
        "itemsperpage"?: number;
    }
    interface IntrinsicElements {
        "composable-table": ComposableTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "composable-table": LocalJSX.ComposableTable & JSXBase.HTMLAttributes<HTMLComposableTableElement>;
        }
    }
}
